export const GIFFS = {
  changePassword: require('./change-password.gif'),
  coupon: require('./coupon.gif'),
  deleteAccount: require('./delete-account.gif'),
  emptyData: require('./empty-data.gif'),
  kesanPesan: require('./kesan-pesan.gif'),
  limitedAccess: require('./limited-acces.gif'),
  limitedOtp: require('./limited-otp.gif'),
  linkSent: require('./link-sent.gif'),
  locked: require('./lock.gif'),
  maintenance: require('./maintenance.gif'),
  offline: require('./offline.gif'),
  paymentComplete: require('./payment-complete.gif'),
  quotaFull: require('./quota-full.gif'),
  splashLogo: require('./logo-opening.gif'),
  successChangePassword: require('./success-change-password.gif'),
  successSignForm: require('./success-sign-form.gif'),
  successSubmitForm: require('./success-submit-form.gif'),
  successFaceID: require('./success-face-id.gif'),
  updateCodepush: require('./update-screen.gif'),
  welcome: require('./welcome.gif'),
  welcomeMpls: require('./welcome-mpls.gif'),
  updateApps: require('./update-apps-chicken.gif'),
  errorPage: require('./error-page.gif'),
};
